controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True

    # DWB controller parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True

      # ✅ Define critics properly as sub-parameters
      critics:
        - RotateToGoal
        - Oscillation
        - BaseObstacle
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist

      RotateToGoal:
        plugin: "dwb_critics::RotateToGoalCritic"
        scale: 32.0
        slowing_factor: 5.0
        lookahead_time: -1.0

      Oscillation:
        plugin: "dwb_critics::OscillationCritic"
        scale: 0.01

      BaseObstacle:
        plugin: "dwb_critics::ObstacleFootprintCritic"
        scale: 0.1

      GoalAlign:
        plugin: "dwb_critics::GoalAlignCritic"
        scale: 24.0
        forward_point_distance: 0.1

      PathAlign:
        plugin: "dwb_critics::PathAlignCritic"
        scale: 32.0
        forward_point_distance: 0.1

      PathDist:
        plugin: "dwb_critics::PathDistCritic"
        scale: 32.0

      GoalDist:
        plugin: "dwb_critics::GoalDistCritic"
        scale: 24.0
